version: 0.2

phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:

      - echo Running GO lint tests
      # Ensure code passes all lint tests
      - golint -set_exit_status
      - echo Running go tests
      # Run all tests included with our application
      - go test
  build:
    commands:

     commands:
      - echo Entered the build phase...
      - echo Build started on `date`

artifacts:
  files:
    - '**/*'