version: 0.2

phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`

artifacts:
  files:
    - '**/*'