version: 0.2

env:
  variables:
    PACKAGE: "github.com/AnimeshChaudhry/github-aws-cicd"

phases:

  install:
    runtime-versions:
        golang: latest
    commands:
      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our 
      # application source code into that directory structure.
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}" 

      # binary will be $(go env GOPATH)/bin/golangci-lint
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.0
      # or install it into ./bin/
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.37.0
      # In alpine linux (as it does not come with curl by default)
      wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.37.0
      golangci-lint --version

  pre_build: 
    commands:

      # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/${PACKAGE}"

      # Fetch all dependencies
      - go get -t ./...

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Check the Go code for common problems with 'go vet'
      - go vet .

      # Run all tests included with our application
      - go test .

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`


artifacts:
  files:
    - '**/*'